---

- block:
    - when: matrix_mautrix_instagram_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"

    - when: matrix_mautrix_instagram_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/setup_install.yml"
  tags:
    - setup-all
    - setup-mautrix-instagram
    - install-all
    - install-mautrix-instagram

- block:
    - when: not matrix_mautrix_instagram_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/setup_uninstall.yml"
  tags:
    - setup-all
    - setup-mautrix-instagram
