---

- name: Check existence of matrix-grafana service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/matrix-grafana.service"
  register: matrix_grafana_service_stat

- when: matrix_grafana_service_stat.stat.exists | bool
  block:
    - name: Ensure matrix-grafana is stopped
      ansible.builtin.service:
        name: matrix-grafana
        state: stopped
        enabled: false
        daemon_reload: true

    - name: Ensure matrix-grafana.service doesn't exist
      ansible.builtin.file:
        path: "{{ devture_systemd_docker_base_systemd_path }}/matrix-grafana.service"
        state: absent
