

- name: Ensure Gitlab configuration is configured
  ansible.builtin.template:
    src: "{{ role_path }}/templates/gitlab.rb.j2"
    dest: "/etc/gitlab/gitlab.rb"
    mode: 0600
  tags:
    - setup-all
    - install-all

- name: Ensure of Creating a Nginx custom file directory
  ansible.builtin.file:
    path: "{{nginx_custom_file_path}}"
    state: directory
    mode: '0644'
  tags:
    - setup-all
    - install-all



# - name: Ensure which Host is running Gitlab services
#   shell: "pcs resource  status GitlabService"
#   register: pcs_status_gitlab_service
#   when: inventory_hostname in groups['gitlab_servers'][0]

- name: Gitlab service reconfigure
  shell: "gitlab-ctl reconfigure"
  register: gitlab_service_reconfigure_msg
  # ignore_errors: true
  tags:
    - setup-all
    - install-all

- name: Ensure Gitlab Ngnix configuration is configured
  ansible.builtin.template:
    src: "{{ role_path }}/templates/nginx_custom.conf.j2"
    dest: "{{nginx_custom_file_path}}/nginx_custom.conf"
    owner: gitlab-www
    group: gitlab-www
    mode: 0644
  tags:
    - setup-all
    - install-all

- name: Gitlab nginx service restart
  shell: "gitlab-ctl restart nginx"
  register: gitlab_service_restart_nginx_msg
  # ignore_errors: true
  tags:
    - setup-all
    - install-all


