---
# tasks file for gitlab_main




- name: Install, configure, and start Gitlab with Pacemaker
  block:
  - ansible.builtin.include_tasks: "{{ role_path }}/tasks/gitlab_presetup.yml"
  - ansible.builtin.include_tasks: "{{ role_path }}/tasks/gitlab_setup.yml"
  - ansible.builtin.include_tasks: "{{ role_path }}/tasks/pacemaker_setup.yml"
  when: gitlab_enabled | bool 
  tags: always

- name: Update, and restart Gitlab with Pacemaker
  block:
  - ansible.builtin.include_tasks: "{{ role_path }}/tasks/gitlab_update.yml"
  when: gitlab_enabled | bool
  tags:
  - reconfig-gitlab





