---

- block:
    - when: matrix_prometheus_postgres_exporter_enabled | bool and matrix_prometheus_postgres_exporter_metrics_proxying_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/inject_into_nginx_proxy.yml"
  tags:
    - setup-all
    - setup-nginx-proxy
    - install-all
    - install-nginx-proxy

- block:
    - when: matrix_prometheus_postgres_exporter_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"

    - when: matrix_prometheus_postgres_exporter_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/setup_install.yml"
  tags:
    - setup-all
    - setup-prometheus-postgres-exporter
    - install-all
    - install-prometheus-postgres-exporter

- block:
    - when: not matrix_prometheus_postgres_exporter_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/setup_uninstall.yml"
  tags:
    - setup-all
    - setup-prometheus-postgres-exporter
