---
# tasks file for gitlab_storage


- name: Install the Pacemaker & DRBD9 packages 
  ansible.builtin.apt:
    pkg:
    - nfs-kernel-server=1:2.6.1-1ubuntu1.2
  tags:
    - setup-all
    - install-all

- name: Ensure of Creating a NFS directory
  ansible.builtin.file:
    path: "{{nfs_directory}}"
    state: directory
    mode: '755'
  tags:
    - setup-all
    - install-all

- name: Install, configure, and start DRBD with Pacemaker
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/drbd_setup.yml"  
  when: drbd_enabled | bool
  tags: always
  


- name: Ensure NFS configuration is configured
  ansible.builtin.template:
    src: "{{ role_path }}/templates/exports.j2"
    dest: "/etc/exports"
    mode: 0644
  when: inventory_hostname in groups["drbd_primary"]
  tags:
    - setup-all
    - install-all


- name: Restart and enable a NFS server 
  ansible.builtin.systemd:
    name:  nfs-kernel-server.service
    state: restarted
    enabled: true
  register: NFS_service_status
  when: inventory_hostname in groups["drbd_primary"]
  tags:
    - setup-all
    - install-all