---

- name: Check existence of matrix-etherpad service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/matrix-etherpad.service"
  register: matrix_etherpad_service_stat

- when: matrix_etherpad_service_stat.stat.exists | bool
  block:
    - name: Ensure matrix-etherpad is stopped
      ansible.builtin.service:
        name: matrix-etherpad
        state: stopped
        enabled: false
        daemon_reload: true

    - name: Ensure matrix-etherpad.service doesn't exist
      ansible.builtin.file:
        path: "{{ devture_systemd_docker_base_systemd_path }}/matrix-etherpad.service"
        state: absent

    - name: Ensure Etherpad base directory doesn't exist
      ansible.builtin.file:
        path: "{{ matrix_etherpad_base_path }}"
        state: absent
