---

#- name: Ensure certificates is sended to ngnix proxy configuration files. 


- name: Verify certificates
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/ssl/setup_ssl_manually_managed_verify_for_domain.yml"
  with_items: "{{ matrix_ssl_domains_to_obtain_certificates_for | unique }}"
  loop_control:
    loop_var: domain_name
  when: "matrix_ssl_retrieval_method == 'manually-managed' and matrix_wildcard_cerifiate_enabled is not true"
