---

- name: Ensure Matrix jitsi-jvb path exists
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    mode: 0777
    owner: "{{ matrix_user_username }}"
    group: "{{ matrix_user_groupname }}"
  with_items:
    - {path: "{{ matrix_jitsi_jvb_base_path }}", when: true}
    - {path: "{{ matrix_jitsi_jvb_config_path }}", when: true}
  when: item.when | bool

- name: Ensure jitsi-jvb Docker image is pulled
  community.docker.docker_image:
    name: "{{ matrix_jitsi_jvb_docker_image }}"
    source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"
    force_source: "{{ matrix_jitsi_jvb_docker_image_force_pull if ansible_version.major > 2 or ansible_version.minor >= 8 else omit }}"
    force: "{{ omit if ansible_version.major > 2 or ansible_version.minor >= 8 else matrix_jitsi_jvb_docker_image_force_pull }}"
  register: result
  retries: "{{ devture_playbook_help_container_retries_count }}"
  delay: "{{ devture_playbook_help_container_retries_delay }}"
  until: result is not failed

- name: Ensure jitsi-jvb configuration files created
  ansible.builtin.template:
    src: "{{ role_path }}/templates/jvb/{{ item }}.j2"
    dest: "{{ matrix_jitsi_jvb_config_path }}/{{ item }}"
    owner: "{{ matrix_user_username }}"
    group: "{{ matrix_user_groupname }}"
    mode: 0644
  with_items:
    - custom-sip-communicator.properties
    - logging.properties

- name: Ensure jitsi-jvb environment variables file created
  ansible.builtin.template:
    src: "{{ role_path }}/templates/jvb/env.j2"
    dest: "{{ matrix_jitsi_jvb_base_path }}/env"
    owner: "{{ matrix_user_username }}"
    group: "{{ matrix_user_groupname }}"
    mode: 0640

- name: Ensure matrix-jitsi-jvb.service installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/jvb/matrix-jitsi-jvb.service.j2"
    dest: "{{ devture_systemd_docker_base_systemd_path }}/matrix-jitsi-jvb.service"
    mode: 0644
