---

- ansible.builtin.include_role:
    name: matrix/matrix-base
    tasks_from: ensure_openssl_installed

- name: Ensure Matrix jitsi base path exists
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    mode: 0750
    owner: "{{ matrix_user_username }}"
    group: "{{ matrix_user_groupname }}"
  with_items:
    - {path: "{{ matrix_jitsi_base_path }}", when: true}
  when: item.when | bool
