---

- name: Check existence of matrix-jitsi-web service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/matrix-jitsi-web.service"
  register: matrix_jitsi_web_service_stat

- when: matrix_jitsi_web_service_stat.stat.exists | bool
  block:
    - name: Ensure matrix-jitsi-web is stopped
      ansible.builtin.service:
        name: matrix-jitsi-web
        state: stopped
        enabled: false
        daemon_reload: true

    - name: Ensure matrix-jitsi-web.service doesn't exist
      ansible.builtin.file:
        path: "{{ devture_systemd_docker_base_systemd_path }}/matrix-jitsi-web.service"
        state: absent

    - name: Ensure Matrix jitsi-web paths doesn't exist
      ansible.builtin.file:
        path: "{{ matrix_jitsi_web_base_path }}"
        state: absent
