---
- name: Fail if required backup-borg settings not defined
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item.name }}`).
  when: "item.when | bool and vars[item.name] == '' and 'matrix_servers' in group_names " 
  with_items:
    - {'name': 'matrix_backup_borg_ssh_key_private', when: true}
    - {'name': 'matrix_backup_borg_location_repositories', when: true}
    - {'name': 'matrix_backup_borg_postgresql_databases_hostname', when: "{{ matrix_backup_borg_postgresql_enabled }}"}


- name: Fail if required backup-borg settings not defined 
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item.name }}`).
  when: "item.when | bool and vars[item.name] == '' and 'keycloak_servers' in group_names "
  with_items:
    - {'name': 'matrix_backup_borg_ssh_key_private', when: true}
    - {'name': 'keycloak_backup_borg_location_repositories', when: true}
    - {'name': 'keycloak_postgresql_database_hostname', when: "{{ matrix_backup_borg_postgresql_enabled }}"}

- name: Fail if encryption passphrase is undefined unless repository is unencrypted
  ansible.builtin.fail:
    msg: >-
      You need to define a required passphrase using the `matrix_backup_borg_storage_encryption_passphrase` variable.
  when: "matrix_backup_borg_storage_encryption_passphrase == '' and matrix_backup_borg_encryption != 'none'"
