---

- name: Check existence of matrix-ntfy service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/matrix-ntfy.service"
  register: matrix_ntfy_service_stat

- when: matrix_ntfy_service_stat.stat.exists | bool
  block:
    - name: Ensure matrix-ntfy is stopped
      ansible.builtin.service:
        name: matrix-ntfy
        state: stopped
        enabled: false
        daemon_reload: true

    - name: Ensure matrix-ntfy.service doesn't exist
      ansible.builtin.file:
        path: "{{ devture_systemd_docker_base_systemd_path }}/matrix-ntfy.service"
        state: absent

    - name: Ensure matrix-ntfy path doesn't exist
      ansible.builtin.file:
        path: "{{ matrix_ntfy_base_path }}"
        state: absent
